name: Build and Release PresenceApp

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [created, published]

jobs:
  build:
    runs-on: macos-latest  # Run on macOS for macOS-specific builds

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build and Publish Electron App
        run: npm run mwl  # This builds for macOS, Windows, and Linux simultaneously
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
